apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demo-upgrade
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/gtrivedi-tenant/demo-upgrade/demo-upgrade@sha256:5848c2331141ce15e89c484e41b574173a85dde936562c57211db56c10631eef
        name: my-java-springboot
        resources: {}
status: {}
