apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demo-upgrade
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/gtrivedi-tenant/demo-upgrade/demo-upgrade@sha256:90593c6a3b826014d704fc00934cd899991a7bfefae907e0419a2ffc682e64af
        name: my-java-springboot
        resources: {}
status: {}
